### ISSUE TITLE
Consent between first party application .. must be configured via preauthorization

### ISSUE THREAD

**Issue by pawp81** [secureworks/PhishInSuits#1]
I am receiving following error when trying your script:
AADSTS65002: Consent between first party application '9bc3ab49-b65d-410a-85ad-de819febfddc' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.

I run:
python3 pis.py -e myuser@mydomain.com -c 9bc3ab49-b65d-410a-85ad-de819febfddc -G

**Comment by nromsdahl-scwx** [comment]
Some client IDs (like Microsoft) require a tenant to be configured in order to use them with the tool.  We often had better luck with third party client IDs that were still verified.
